// ? NEW INVOICE
export const NEW_INVOICE_REQUEST = "NEW_INVOICE_REQUEST";
export const NEW_INVOICE_SUCCESS = "NEW_INVOICE_SUCCESS";
export const NEW_INVOICE_FAILURE = "NEW_INVOICE_FAILURE";

// ? ALL INVOICES
export const ALL_INVOICES_REQUEST = "ALL_INVOICES_REQUEST";
export const ALL_INVOICES_SUCCESS = "ALL_INVOICES_SUCCESS";
export const ALL_INVOICES_FAILURE = "ALL_INVOICES_FAILURE";

// ? INVOICE DETAILS
export const INVOICE_DETAILS_REQUEST = "INVOICE_DETAILS_REQUEST";
export const INVOICE_DETAILS_SUCCESS = "INVOICE_DETAILS_SUCCESS";
export const INVOICE_DETAILS_FAILURE = "INVOICE_DETAILS_FAILURE";

// ? DELETE INVOICE
export const DELETE_INVOICE_REQUEST = "DELETE_INVOICE_REQUEST";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAILURE = "DELETE_INVOICE_FAILURE";

// ? CLEAR ERRORS
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
