// ? ALL MEDICINES
export const ALL_MEDICINE_REQUEST = "ALL_MEDICINE_REQUEST";
export const ALL_MEDICINE_SUCCESS = "ALL_MEDICINE_SUCCESS";
export const ALL_MEDICINE_FAIL = "ALL_MEDICINE_FAIL";

// ? MEDICINE DETAILS
export const MEDICINE_DETAILS_REQUEST = "MEDICINE_DETAILS_REQUEST";
export const MEDICINE_DETAILS_SUCCESS = "MEDICINE_DETAILS_SUCCESS";
export const MEDICINE_DETAILS_FAIL = "MEDICINE_DETAILS_FAIL";

// ? MEDICINE STOCK DETAILS
export const STOCK_DETAILS_REQUEST = "STOCK_DETAILS_REQUEST";
export const STOCK_DETAILS_SUCCESS = "STOCK_DETAILS_SUCCESS";
export const STOCK_DETAILS_FAIL = "STOCK_DETAILS_FAIL";

// ? MEDICINE STOCK DETAILS
export const MED_STOCK_REQUEST = "MED_STOCK_REQUEST";
export const MED_STOCK_SUCCESS = "MED_STOCK_SUCCESS";
export const MED_STOCK_FAIL = "MED_STOCK_FAIL";

// ? ADD MEDICINE
export const CREATE_MEDICINE_REQUEST = "CREATE_MEDICINE_REQUEST";
export const CREATE_MEDICINE_SUCCESS = "CREATE_MEDICINE_SUCCESS";
export const CREATE_MEDICINE_FAIL = "CREATE_MEDICINE_FAIL";
export const CREATE_MEDICINE_RESET = "CREATE_MEDICINE_RESET";

// ? ADD MEDICINE STOCK DETAILS
export const ADD_MEDICINE_STOCK_REQUEST = "ADD_MEDICINE_STOCK_REQUEST";
export const ADD_MEDICINE_STOCK_SUCCESS = "ADD_MEDICINE_STOCK_SUCCESS";
export const ADD_MEDICINE_STOCK_FAIL = "ADD_MEDICINE_STOCK_FAIL";
export const ADD_MEDICINE_STOCK_RESET = "ADD_MEDICINE_STOCK_RESET";

// ? UPDATE MEDICINE
export const UPDATE_MEDICINE_REQUEST = "UPDATE_MEDICINE_REQUEST";
export const UPDATE_MEDICINE_SUCCESS = "UPDATE_MEDICINE_SUCCESS";
export const UPDATE_MEDICINE_FAIL = "UPDATE_MEDICINE_FAIL";
export const UPDATE_MEDICINE_RESET = "UPDATE_MEDICINE_RESET";

// ? UPDATE MEDICINE STOCK DETAILS
export const UPDATE_MEDICINE_STOCK_REQUEST = "UPDATE_MEDICINE_STOCK_REQUEST";
export const UPDATE_MEDICINE_STOCK_SUCCESS = "UPDATE_MEDICINE_STOCK_SUCCESS";
export const UPDATE_MEDICINE_STOCK_FAIL = "UPDATE_MEDICINE_STOCK_FAIL";
export const UPDATE_MEDICINE_STOCK_RESET = "UPDATE_MEDICINE_STOCK_RESET";

// ? DELETE MEDICINE
export const DELETE_MEDICINE_REQUEST = "DELETE_MEDICINE_REQUEST";
export const DELETE_MEDICINE_SUCCESS = "DELETE_MEDICINE_SUCCESS";
export const DELETE_MEDICINE_FAIL = "DELETE_MEDICINE_FAIL";
export const DELETE_MEDICINE_RESET = "DELETE_MEDICINE_RESET";

// ? DELETE MEDICINE STOCK DETAILS
export const DELETE_MEDICINE_STOCK_REQUEST = "DELETE_MEDICINE_STOCK_REQUEST";
export const DELETE_MEDICINE_STOCK_SUCCESS = "DELETE_MEDICINE_STOCK_SUCCESS";
export const DELETE_MEDICINE_STOCK_FAIL = "DELETE_MEDICINE_STOCK_FAIL";

// ? CLEAR ERRORS
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
